import os

CORS_HEADERS = 'Content-Type'
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS= False
PROPAGATE_EXCEPTIONS=True
MAX_CONTENT_LENGTH = 16 * 1024 * 1024
UPLOADED_IMAGES_DEST = os.path.join("static", "images")