"""initial commit

Revision ID: 31833fa76faf
Revises: 
Create Date: 2020-07-16 06:16:23.970427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31833fa76faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pasillos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camaras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('pasillo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pasillo_id'], ['pasillos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camara_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('total_boxes', sa.Integer(), nullable=True),
    sa.Column('area_boxes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camara_id'], ['camaras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuadrados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediccion_id', sa.Integer(), nullable=True),
    sa.Column('clase', sa.Integer(), nullable=True),
    sa.Column('center_x', sa.Integer(), nullable=True),
    sa.Column('center_y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['prediccion_id'], ['predicciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediccion_id', sa.Integer(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['prediccion_id'], ['predicciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos')
    op.drop_table('cuadrados')
    op.drop_table('predicciones')
    op.drop_table('camaras')
    op.drop_table('pasillos')
    # ### end Alembic commands ###
