"""tabla foto eliminada

Revision ID: 388545203929
Revises: 934f37ef1dcd
Create Date: 2020-07-17 17:13:11.433998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388545203929'
down_revision = '934f37ef1dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camara_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ruta', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['camara_id'], ['camaras.id'], name='fotos_camara_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fotos_pkey')
    )
    # ### end Alembic commands ###
