"""agregar columna numero en tabla pasillo

Revision ID: 65ce0c9c14c6
Revises: 31833fa76faf
Create Date: 2020-07-16 21:04:28.308430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ce0c9c14c6'
down_revision = '31833fa76faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pasillos', sa.Column('numero', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pasillos', 'numero')
    # ### end Alembic commands ###
