"""cambio tabala fotos prediccion_id -> camara_id

Revision ID: 934f37ef1dcd
Revises: c1cb3108adbe
Create Date: 2020-07-17 17:07:47.806543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '934f37ef1dcd'
down_revision = 'c1cb3108adbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fotos', sa.Column('camara_id', sa.Integer(), nullable=True))
    op.add_column('fotos', sa.Column('ruta', sa.String(length=255), nullable=True))
    op.drop_constraint('fotos_prediccion_id_fkey', 'fotos', type_='foreignkey')
    op.create_foreign_key(None, 'fotos', 'camaras', ['camara_id'], ['id'])
    op.drop_column('fotos', 'foto')
    op.drop_column('fotos', 'prediccion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fotos', sa.Column('prediccion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fotos', sa.Column('foto', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fotos', type_='foreignkey')
    op.create_foreign_key('fotos_prediccion_id_fkey', 'fotos', 'predicciones', ['prediccion_id'], ['id'])
    op.drop_column('fotos', 'ruta')
    op.drop_column('fotos', 'camara_id')
    # ### end Alembic commands ###
