"""columns in prediccion and cuadrado cant be null

Revision ID: c1cb3108adbe
Revises: fd9876b91ba4
Create Date: 2020-07-17 17:29:47.155073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1cb3108adbe'
down_revision = 'fd9876b91ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cuadrados', 'accuracy',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cuadrados', 'center_x',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cuadrados', 'center_y',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cuadrados', 'clase',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cuadrados', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cuadrados', 'prediccion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cuadrados', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('predicciones', 'area_boxes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('predicciones', 'camara_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('predicciones', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('predicciones', 'total_boxes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predicciones', 'total_boxes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('predicciones', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('predicciones', 'camara_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('predicciones', 'area_boxes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cuadrados', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cuadrados', 'prediccion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cuadrados', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cuadrados', 'clase',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cuadrados', 'center_y',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cuadrados', 'center_x',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cuadrados', 'accuracy',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
