"""Fixed camara path

Revision ID: fd9876b91ba4
Revises: af26fd67fea9
Create Date: 2020-07-16 23:40:40.876241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9876b91ba4'
down_revision = 'af26fd67fea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camaras', 'pasillo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camaras', 'pasillo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
