"""empty message

Revision ID: fe10ac1ce6b2
Revises: 388545203929
Create Date: 2020-09-24 18:47:19.002291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe10ac1ce6b2'
down_revision = '388545203929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pasillos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camaras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('pasillo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pasillo_id'], ['pasillos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasillo_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('coordinates', sa.String(length=255), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pasillo_id'], ['pasillos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuadrados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediccion_id', sa.Integer(), nullable=False),
    sa.Column('clase', sa.Integer(), nullable=False),
    sa.Column('center_x', sa.Integer(), nullable=False),
    sa.Column('center_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['prediccion_id'], ['predicciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuadrados')
    op.drop_table('predicciones')
    op.drop_table('productos')
    op.drop_table('camaras')
    op.drop_table('pasillos')
    # ### end Alembic commands ###
